[package]
authors = ["Johan Brinch <johan@pleo.io>"]
edition = "2018"
name = "klima"
version = "0.1.0"
[dependencies]
failure = "*"
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }
