[package]
authors = ["Johan Brinch <johan@pleo.io>"]
edition = "2018"
name = "klima"
version = "0.1.0"
[dependencies]
failure = "*"
im = "*"
serde_json = "*"

[dependencies.serde]
features = ["derive"]
version = "1.0"
